In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Data/November_MyCall_2022.csv")
df1 = pd.read_csv("data/December_MyCall_2022.csv")
df2 = pd.read_csv('data/January_MyCall_2023.csv')
df3 = pd.read_csv("data/February_MyCall_2023.csv")
df4 = pd.read_csv("data/March_MyCall_2023.csv")
df5 = pd.read_csv("data/April_MyCall_2023.csv")
df6 = pd.read_csv("data/March_MyCall_2023.csv")
df7 = pd.read_csv("data/June_MyCall_2023.csv")
df8 = pd.read_csv("data/July_MyCall_2023.csv")
df9 = pd.read_csv("data/August_MyCall_2023.csv")
df10 = pd.read_csv("data/September_MyCall_2023.csv")
df11 = pd.read_csv("data/October_MyCall_2023.csv")

In [4]:
df["month"] = "November"
df1["month"] = "December"
df2["month"] = "January"
df3["month"] = "February"
df4["month"] = "March"
df5["month"] = "April"
df6["month"] = "May"
df7["month"] = "June"
df8["month"] = "July"
df9["month"] = "August"
df10["month"] = "September"
df11["month"] = "October"

In [5]:
dataframes = [df , df1 , df2, df3 , df4, df5, df6 , df7 , df8, df9 , df10 , df11]

for i in dataframes:
    print(i.shape)

(1118, 9)
(1370, 9)
(660, 9)
(577, 9)
(1002, 9)
(475, 9)
(1002, 9)
(527, 9)
(531, 9)
(327, 9)
(370, 9)
(167, 9)

In [6]:
data = pd.concat(dataframes)

In [7]:
data.head()

,operator,inout_travelling,network_type,rating,calldrop_category,latitude,longitude,state_name,month
0,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November
1,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November
2,VI,Indoor,Unknown,5,Satisfactory,-1.0,-1.0,NaN,November
3,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November
4,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November

In [8]:
data.shape

(8126, 9)

In [9]:
data.isnull().sum()

operator                0
inout_travelling        0
network_type            0
rating                  0
calldrop_category       0
latitude                0
longitude               0
state_name           3156
month                   0
dtype: int64

In [10]:
data["year"] = data["month"].apply(lambda x: 2022 if x in ["November", "December"] else 2023)

In [11]:
data.head()

,operator,inout_travelling,network_type,rating,calldrop_category,latitude,longitude,state_name,month,year
0,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
1,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
2,VI,Indoor,Unknown,5,Satisfactory,-1.0,-1.0,NaN,November,2022
3,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
4,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022

### we have successfully created our data in organize form

- lets begin with some basic statistical analysis of our data

In [12]:
data.shape

(8126, 10)

In [13]:
data.columns

Index(['operator', 'inout_travelling', 'network_type', 'rating',
       'calldrop_category', 'latitude', 'longitude', 'state_name', 'month',
       'year'],
      dtype='object')

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8126 entries, 0 to 166
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   operator           8126 non-null   object
 1   inout_travelling   8126 non-null   object
 2   network_type       8126 non-null   object
 3   rating             8126 non-null   int64
 4   calldrop_category  8126 non-null   object
 5   latitude           8126 non-null   float64
 6   longitude          8126 non-null   float64
 7   state_name         4970 non-null   object
 8   month              8126 non-null   object
 9   year               8126 non-null   int64
dtypes: float64(2), int64(2), object(6)
memory usage: 698.3+ KB

In [15]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
rating,8126.0,3.393059,1.566282,1.0,2.0,4.000000,5.000000,5.000000
latitude,8126.0,11.600513,11.415273,-1.0,-1.0,12.956596,19.220111,32.988897
longitude,8126.0,46.644564,38.052408,-1.1,-1.0,73.001939,77.589436,91.100949
year,8126.0,2022.693822,0.460933,2022.0,2022.0,2023.000000,2023.000000,2023.000000

In [16]:
data.isnull().sum()

operator                0
inout_travelling        0
network_type            0
rating                  0
calldrop_category       0
latitude                0
longitude               0
state_name           3156
month                   0
year                    0
dtype: int64

In [17]:
data.duplicated().sum()

3644

In [18]:
data[data.duplicated()].head(30)

,operator,inout_travelling,network_type,rating,calldrop_category,latitude,longitude,state_name,month,year
1,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
3,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
4,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
5,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
6,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
7,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
8,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
9,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
10,VI,Indoor,Unknown,5,Satisfactory,-1.0,-1.0,NaN,November,2022
11,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
15,RJio,Indoor,4G,1,Poor Voice Quality,-1.0,-1.0,NaN,November,2022
19,Airtel,Indoor,4G,1,Poor Voice Quality,-1.0,-1.0,NaN,November,2022
21,Airtel,Indoor,4G,1,Poor Voice Quality,-1.0,-1.0,NaN,November,2022
23,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
24,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
25,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
26,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
27,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
28,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
29,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
30,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
31,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
32,VI,Indoor,Unknown,5,Satisfactory,-1.0,-1.0,NaN,November,2022
33,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
34,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
35,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
36,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
37,VI,Indoor,4G,5,Satisfactory,-1.0,-1.0,NaN,November,2022
47,Airtel,Indoor,4G,1,Poor Voice Quality,-1.0,-1.0,NaN,November,2022
49,RJio,Indoor,Unknown,1,Poor Voice Quality,-1.0,-1.0,NaN,November,2022

In [19]:
data[data["month"] == "November"].head(60)

,operator,inout_travelling,network_type,rating,calldrop_category,latitude,longitude,state_name,month,year
0,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
1,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
2,VI,Indoor,Unknown,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
3,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
4,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
5,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
6,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
7,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
8,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
9,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
10,VI,Indoor,Unknown,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
11,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
12,RJio,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
13,Airtel,Indoor,Unknown,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
14,RJio,Indoor,4G,1,Poor Voice Quality,-1.000000,-1.000000,NaN,November,2022
15,RJio,Indoor,4G,1,Poor Voice Quality,-1.000000,-1.000000,NaN,November,2022
16,VI,Indoor,4G,1,Call Dropped,-1.000000,-1.000000,NaN,November,2022
17,RJio,Indoor,4G,1,Call Dropped,-1.000000,-1.000000,NaN,November,2022
18,Airtel,Indoor,4G,1,Poor Voice Quality,-1.000000,-1.000000,NaN,November,2022
19,Airtel,Indoor,4G,1,Poor Voice Quality,-1.000000,-1.000000,NaN,November,2022
20,VI,Indoor,4G,5,Satisfactory,18.508186,73.833598,Maharashtra,November,2022
21,Airtel,Indoor,4G,1,Poor Voice Quality,-1.000000,-1.000000,NaN,November,2022
22,VI,Indoor,4G,5,Satisfactory,18.507952,73.834063,Maharashtra,November,2022
23,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
24,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
25,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
26,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
27,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
28,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
29,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
30,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
31,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
32,VI,Indoor,Unknown,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
33,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
34,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
35,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
36,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
37,VI,Indoor,4G,5,Satisfactory,-1.000000,-1.000000,NaN,November,2022
38,Airtel,Indoor,4G,1,Call Dropped,19.220563,72.842909,Maharashtra,November,2022
39,Airtel,Indoor,Unknown,5,Satisfactory,13.072318,77.560497,Karnataka,November,2022
40,Airtel,Indoor,4G,5,Satisfactory,13.071719,77.560556,Karnataka,November,2022
41,RJio,Indoor,4G,5,Satisfactory,26.898877,75.816674,Rajasthan,November,2022
42,Airtel,Outdoor,Unknown,1,Poor Voice Quality,19.220558,72.842899,Maharashtra,November,2022
43,Airtel,Indoor,4G,3,Satisfactory,19.220548,72.842859,Maharashtra,November,2022
44,VI,Indoor,Unknown,5,Satisfactory,25.257093,86.999417,Bihar,November,2022
45,VI,Indoor,Unknown,5,Satisfactory,25.257685,87.000096,Bihar,November,2022
46,VI,Indoor,4G,5,Satisfactory,25.257321,87.000409,Bihar,November,2022
47,Airtel,Indoor,4G,1,Poor Voice Quality,-1.000000,-1.000000,NaN,November,2022
48,RJio,Indoor,Unknown,1,Poor Voice Quality,-1.000000,-1.000000,NaN,November,2022
49,RJio,Indoor,Unknown,1,Poor Voice Quality,-1.000000,-1.000000,NaN,November,2022
50,VI,Indoor,Unknown,1,Poor Voice Quality,-1.000000,-1.000000,NaN,November,2022
51,RJio,Indoor,Unknown,1,Poor Voice Quality,-1.000000,-1.000000,NaN,November,2022
52,VI,Indoor,4G,1,Poor Voice Quality,-1.000000,-1.000000,NaN,November,2022
53,Airtel,Indoor,Unknown,5,Satisfactory,13.072762,77.560290,Karnataka,November,2022
54,Airtel,Outdoor,4G,3,Satisfactory,30.104795,78.287660,Uttarakhand,November,2022
55,Airtel,Indoor,Unknown,5,Satisfactory,13.072593,77.560208,Karnataka,November,2022
56,Airtel,Indoor,4G,5,Satisfactory,13.072595,77.560207,Karnataka,November,2022
57,RJio,Indoor,4G,1,Poor Voice Quality,25.466450,81.849586,Uttar Pradesh,November,2022
58,RJio,Indoor,4G,1,Poor Voice Quality,-1.000000,-1.000000,NaN,November,2022
59,Airtel,Indoor,4G,1,Poor Voice Quality,-1.000000,-1.000000,NaN,November,2022

In [20]:
data.drop_duplicates(inplace=True)

In [21]:
data.duplicated().sum()

0

In [22]:
data.shape

(4482, 10)